name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.0.1'
      SERVERPOD_PASSWORD_database: '_g7O-Tl-kQ4nc3ts0MMeh2hauF8P2Jr2'
      SERVERPOD_PASSWORD_redis: 'prV4FnUCDiBBvxY-TakK9fOeZosfi5FK'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: serverpod_hackathon_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: serverpod_hackathon_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: serverpod_hackathon_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: serverpod_hackathon_server
        run: serverpod generate

      - name: Run tests
        working-directory: serverpod_hackathon_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: serverpod_hackathon_server
        run: docker compose down -v
